apiVersion: v1
kind: Service
metadata:
  name: app-service1
  labels:
    app: demo-app
spec:
  selector:
    app: demo-app
  ports:
    - protocol: 'TCP'
      name: web
      port: 5000
      targetPort: 3000
  type: NodePort